// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTools.SchedulerService.Data;

namespace NTools.SchedulerService.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("NTools.SchedulerService.Data.Model.SchedulerTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastRunTime");

                    b.Property<DateTime>("NextRunTime");

                    b.Property<string>("Scheduler");

                    b.Property<string>("TaskEngine");

                    b.HasKey("Id");

                    b.ToTable("SchedulerTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
